FROM python:3.10

WORKDIR /app
COPY frontend /app/frontend
COPY requirements.txt /app

RUN pip install --upgrade pip && pip install -r requirements.txt

EXPOSE 8501

CMD ["streamlit", "run", "frontend/streamlit_app.py", "--server.port=8501", "--server.address=0.0.0.0"]